### ISSUE TITLE
Specify vagrant ^v1.7.0

### ISSUE THREAD

**Issue by selbekk** [Sardtok/elk-workshop-vm#1]
When running `vagrant up` for the first time, I get the following output:

```
/workshops/elk-workshop-vm on master $ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'mast3rof0/lubuntu32' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'mast3rof0/lubuntu32'
    default: URL: https://vagrantcloud.com/mast3rof0/lubuntu32
==> default: Adding box 'mast3rof0/lubuntu32' (v14.04.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/mast3rof0/boxes/lubuntu32/versions/14.04.1/providers/virtualbox.box
==> default: Successfully added box 'mast3rof0/lubuntu32' (v14.04.1) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'fix-no-tty' provisioner could not be found.
```

Successive calls to `vagrant up` ends up showing the error alone. After deleting the vm with `vagrant destroy` and then running `vagrant up` I get the error alone. 

---

After some quick research I found [this post](http://stackoverflow.com/questions/30899455/error-message-the-fix-no-tty-provisioner-could-not-be-found-when-i-vagrant-up), letting me know I needed v1.7.0 or above to make this work. 

Would've saved me 10 minutes if I already knew this from the manual :)

**Comment by Sardtok** [comment]
Sorry, I was not aware that named provisioners was that new a feature. I have only tested it with the latest version 1.8.5. I'll add a version requirement in the Vagrantfile as well, so it stops with an appropriate error message.
